### ISSUE TITLE
suggestion add a mod icon

### ISSUE THREAD

**Issue by CatsArmy** [rtpoogle/GoAwayModList#1]
nothin too crazy if you wana be really lazy just yoink the icon of hidemodlist but it don really matter i feel like just having one is nice

**Comment by rtpoogle** [comment]
Unfortunately I can't find contact info for Sv_Matt anywhere, otherwise I would love to use the original icon.
I'll just put together a quick icon so it's not just a black square for now, thanks for the suggestion!
